# Generated by Django 2.2.7 on 2019-11-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=1000)),
                ('created_date', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
